In [3]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
C = A.sum(axis=0)
print(C)

[12 15 18]


In [9]:
ans = 100 * A / C.reshape(1,3) #Broadcasting
print(ans)

[[ 8.33333333 13.33333333 16.66666667]
 [33.33333333 33.33333333 33.33333333]
 [58.33333333 53.33333333 50.        ]]


In [10]:
B = A + np.array([1,1,1])  #Broadcasting
print(B)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
