In [1]:
import numpy as np

A = np.random.rand(5) #Rank1 vector. Don't use this in Deeplearning code.

print(A)

[0.71517409 0.92848404 0.75836429 0.92242691 0.92639383]


In [3]:
print(A.T)
print(np.dot(A, A.T))

[0.71517409 0.92848404 0.75836429 0.92242691 0.92639383]
3.6577499154742648


In [4]:
B = np.random.rand(5,1) # Use this instead 
print(B)
print(B.T)
print(np.dot(B, B.T))

[[0.46355895]
 [0.728365  ]
 [0.63226284]
 [0.09532311]
 [0.52292312]]
[[0.46355895 0.728365   0.63226284 0.09532311 0.52292312]]
[[0.2148869  0.33764012 0.2930911  0.04418788 0.24240569]
 [0.33764012 0.53051557 0.46051812 0.06943002 0.3808789 ]
 [0.2930911  0.46051812 0.39975629 0.06026926 0.33062485]
 [0.04418788 0.06943002 0.06026926 0.00908649 0.04984666]
 [0.24240569 0.3808789  0.33062485 0.04984666 0.27344858]]
